############################
# --- Required options --- #
############################

# Name of website
title: Embodied Intelligence Applications

# Your name to show in the footer
author: Some Person

################
# --- Logo --- #
################

# Removing avatar and navigation bar settings

###########################
# --- General options --- #
###########################

# Removing social media and navigation links

# Basic color scheme
page-col: "#FFFFFF"
text-col: "#404040"

# Default YAML values
defaults:
  -
    scope:
      path: "" # this will apply to all pages
    values:
      layout: "default" # we'll create a custom default layout

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-sitemap

# Output options
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
